#
# Copyright (c) 2015-2019, NVIDIA CORPORATION. All rights reserved.
#
# See LICENSE.txt for license information
#
.PHONY : all clean

all:
	${MAKE} -C src  $*
	${MAKE} -C tests  $*

clean:
	${MAKE} -C src $*


